apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pvName }}
spec:
  capacity:
    storage: {{ .Values.nfs.storage }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}