apiVersion: v1
kind: Service
metadata:
  name: exercise-manager
  labels:
    app: exercise-manager
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: http
  selector:
    app: exercise-manager